#
# distrobox assemble create --replace --file ~/Dev/jack/nixos-configs/hosts/bazzite/distrobox.ini
#

[nix-toolbox]
image=fedora-toolbox:latest
name=nix-toolbox
init=true
nvidia=true
home="/home/jack/Toolbox"
volume="/home/jack/Dev:/home/jack/Toolbox/Dev:rw"
volume="/home/jack/Notes:/home/jack/Toolbox/Notes:rw"
additional_packages="fish zsh nix nix-daemon"
pre_init_hooks="export SHELL=/usr/bin/fish;"
init_hooks="sudo systemctl enable --now nix-daemon;"
