#
# mkdir -p ~/Toolbox
# podman build -t local/nix-distrobox:latest ~/Dev/jack/nixos-configs
# distrobox assemble create --replace --file ~/Dev/jack/nixos-configs/hosts/bazzite/distrobox.ini
# distrobox enter nix-toolbox
# cd ~/Dev/jack/nixos-configs-private && nix run home-manager -- switch --flake .

# broken-ish, nix daemon needs manual setup.
# [nix-toolbox]
# name=nix-toolbox
# #hostname=nix-toolbox
# image=fedora-toolbox:latest
# init=true
# nvidia=true
# home="/home/jack/Toolbox"
# additional_packages="fish systemd nix nix-daemon"
# # volume="/var/home/jack/.ssh:/home/jack/Toolbox/.ssh:ro"
# # volume="/var/home/jack/Dev:/home/jack/Toolbox/Dev:rw"
# # volume="/var/home/jack/Downloads:/home/jack/Toolbox/Downloads:rw"
# # volume="/var/home/jack/Notes:/home/jack/Toolbox/Notes:rw"
# pre_init_hooks="ln -sfn /home/jack/.ssh /home/jack/Toolbox/.ssh;"
# pre_init_hooks="ln -sfn /home/jack/Dev /home/jack/Toolbox/Dev;"
# pre_init_hooks="ln -sfn /home/jack/Downloads /home/jack/Toolbox/Downloads;"
# pre_init_hooks="ln -sfn /home/jack/Notes /home/jack/Toolbox/Notes;"
# init_hooks="sudo systemctl enable --now nix-daemon;"
# init_hooks="chsh jack -s /usr/bin/fish;"

[nix-toolbox]
image=local/nix-distrobox:latest
init=true
nvidia=true
home="/home/jack/Toolbox"
pre_init_hooks="usermod -aG nix-users jack;"
pre_init_hooks="chown -R -h jack:jack /home/jack/Toolbox;"
pre_init_hooks="ln -sfn /home/jack/.ssh /home/jack/Toolbox/.ssh;"
pre_init_hooks="ln -sfn /home/jack/Dev /home/jack/Toolbox/Dev;"
pre_init_hooks="ln -sfn /home/jack/Downloads /home/jack/Toolbox/Downloads;"
pre_init_hooks="ln -sfn /home/jack/Notes /home/jack/Toolbox/Notes;"
#init_hooks="runuser -l jack -c /usr/local/bin/container-bootstrap;"
#init_hooks="su jack -c \"nix profile install github:nix-community/nixGL --impure\";"
#init_hooks="su jack -c \"nix profile install nixpkgs#home-manager\";"
#init_hooks="chsh jack -s /usr/bin/fish;"

#[nixos-toolbox]
#name=nixos-toolbox
##hostname=nix-toolbox
#image=nixos/nixos:25.05
#init=true
#nvidia=true
#home="/home/jack/Toolbox"
##additional_packages="fish systemd nix nix-daemon"
#pre_init_hooks="ln -sfn /home/jack/.ssh /home/jack/Toolbox/.ssh;"
#pre_init_hooks="ln -sfn /home/jack/Dev /home/jack/Toolbox/Dev;"
#pre_init_hooks="ln -sfn /home/jack/Downloads /home/jack/Toolbox/Downloads;"
#pre_init_hooks="ln -sfn /home/jack/Notes /home/jack/Toolbox/Notes;"

# daemon starts, maybe works? needs sudo
[nix-debian]
name=nix-debian
#hostname=nix-toolbox
image=debian:stable
init=true
#nvidia=true
home="/home/jack/Toolbox"
additional_packages="fish systemd libpam-systemd nix-setup-systemd"
#additional_packages="pipewire-audio-client-libraries"
# volume="/var/home/jack/.ssh:/home/jack/Toolbox/.ssh:ro"
# volume="/var/home/jack/Dev:/home/jack/Toolbox/Dev:rw"
# volume="/var/home/jack/Downloads:/home/jack/Toolbox/Downloads:rw"
# volume="/var/home/jack/Notes:/home/jack/Toolbox/Notes:rw"
pre_init_hooks="ln -sfn /home/jack/.ssh /home/jack/Toolbox/.ssh;"
pre_init_hooks="ln -sfn /home/jack/Dev /home/jack/Toolbox/Dev;"
pre_init_hooks="ln -sfn /home/jack/Downloads /home/jack/Toolbox/Downloads;"
pre_init_hooks="ln -sfn /home/jack/Notes /home/jack/Toolbox/Notes;"
#nit_hooks="su jack -c bash 'sudo dnf install nix nix-daemon -y; sudo systemctl enable --now nix-daemon';"
#init_hooks="chsh jack -s /usr/bin/fish;"
# init_hooks="nix run --extra-experimental-features \"nix-command flakes\" nixpkgs#cowsay"

# install doesn't complete.
[nix-debian-determinate]
name=nix-debian-determinate
#hostname=nix-toolbox
image=debian:stable
init=true
#nvidia=true
home="/home/jack/Toolbox"
additional_packages="fish systemd libpam-systemd"
#additional_packages="pipewire-audio-client-libraries"
# volume="/var/home/jack/.ssh:/home/jack/Toolbox/.ssh:ro"
# volume="/var/home/jack/Dev:/home/jack/Toolbox/Dev:rw"
# volume="/var/home/jack/Downloads:/home/jack/Toolbox/Downloads:rw"
# volume="/var/home/jack/Notes:/home/jack/Toolbox/Notes:rw"
pre_init_hooks="ln -sfn /home/jack/.ssh /home/jack/Toolbox/.ssh;"
pre_init_hooks="ln -sfn /home/jack/Dev /home/jack/Toolbox/Dev;"
pre_init_hooks="ln -sfn /home/jack/Downloads /home/jack/Toolbox/Downloads;"
pre_init_hooks="ln -sfn /home/jack/Notes /home/jack/Toolbox/Notes;"
#nit_hooks="su jack -c bash 'sudo dnf install nix nix-daemon -y; sudo systemctl enable --now nix-daemon';"
#init_hooks="chsh jack -s /usr/bin/fish;"
init_hooks="curl -fsSL https://install.determinate.systems/nix | sh -s -- install --no-confirm --prefer-upstream-nix"
